#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamDataGridSample.Droid.Resource", IsApplication=true)]

namespace XamDataGridSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::DevExpress.Mobile.Core.Android.Resource.String.library_name = global::XamDataGridSample.Droid.Resource.String.library_name;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Color.black = global::XamDataGridSample.Droid.Resource.Color.black;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Color.blue = global::XamDataGridSample.Droid.Resource.Color.blue;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Color.gray = global::XamDataGridSample.Droid.Resource.Color.gray;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Color.green = global::XamDataGridSample.Droid.Resource.Color.green;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Color.red = global::XamDataGridSample.Droid.Resource.Color.red;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Color.theme_dark_segmented_radio_button_text = global::XamDataGridSample.Droid.Resource.Color.theme_dark_segmented_radio_button_text;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Color.theme_default_segmented_radio_button_text = global::XamDataGridSample.Droid.Resource.Color.theme_default_segmented_radio_button_text;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_grey = global::XamDataGridSample.Droid.Resource.Drawable.segment_grey;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_grey_focus = global::XamDataGridSample.Droid.Resource.Drawable.segment_grey_focus;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_grey_press = global::XamDataGridSample.Droid.Resource.Drawable.segment_grey_press;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_left_off = global::XamDataGridSample.Droid.Resource.Drawable.segment_left_off;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_left_off_pressed = global::XamDataGridSample.Droid.Resource.Drawable.segment_left_off_pressed;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_left_on = global::XamDataGridSample.Droid.Resource.Drawable.segment_left_on;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_middle_off = global::XamDataGridSample.Droid.Resource.Drawable.segment_middle_off;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_middle_off_pressed = global::XamDataGridSample.Droid.Resource.Drawable.segment_middle_off_pressed;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_middle_on = global::XamDataGridSample.Droid.Resource.Drawable.segment_middle_on;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_off = global::XamDataGridSample.Droid.Resource.Drawable.segment_off;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_off_pressed = global::XamDataGridSample.Droid.Resource.Drawable.segment_off_pressed;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_on = global::XamDataGridSample.Droid.Resource.Drawable.segment_on;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_grey_left = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_grey_left;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_grey_left_focus = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_grey_left_focus;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_grey_left_press = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_grey_left_press;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_grey_middle = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_grey_middle;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_grey_middle_focus = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_grey_middle_focus;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_grey_middle_press = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_grey_middle_press;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_grey_right = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_grey_right;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_grey_right_focus = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_grey_right_focus;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_grey_right_press = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_grey_right_press;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_white_left = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_white_left;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_white_left_focus = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_white_left_focus;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_white_left_press = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_white_left_press;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_white_middle = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_white_middle;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_white_middle_focus = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_white_middle_focus;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_white_middle_press = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_white_middle_press;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_white_right = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_white_right;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_white_right_focus = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_white_right_focus;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_radio_white_right_press = global::XamDataGridSample.Droid.Resource.Drawable.segment_radio_white_right_press;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_right_off = global::XamDataGridSample.Droid.Resource.Drawable.segment_right_off;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_right_off_pressed = global::XamDataGridSample.Droid.Resource.Drawable.segment_right_off_pressed;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_right_on = global::XamDataGridSample.Droid.Resource.Drawable.segment_right_on;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_white = global::XamDataGridSample.Droid.Resource.Drawable.segment_white;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_white_focus = global::XamDataGridSample.Droid.Resource.Drawable.segment_white_focus;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.segment_white_press = global::XamDataGridSample.Droid.Resource.Drawable.segment_white_press;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.theme_dark_segment_button = global::XamDataGridSample.Droid.Resource.Drawable.theme_dark_segment_button;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.theme_dark_segment_radio_left = global::XamDataGridSample.Droid.Resource.Drawable.theme_dark_segment_radio_left;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.theme_dark_segment_radio_middle = global::XamDataGridSample.Droid.Resource.Drawable.theme_dark_segment_radio_middle;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.theme_dark_segment_radio_right = global::XamDataGridSample.Droid.Resource.Drawable.theme_dark_segment_radio_right;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.theme_default_segment_button = global::XamDataGridSample.Droid.Resource.Drawable.theme_default_segment_button;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.theme_default_segment_radio_left = global::XamDataGridSample.Droid.Resource.Drawable.theme_default_segment_radio_left;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.theme_default_segment_radio_middle = global::XamDataGridSample.Droid.Resource.Drawable.theme_default_segment_radio_middle;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Drawable.theme_default_segment_radio_right = global::XamDataGridSample.Droid.Resource.Drawable.theme_default_segment_radio_right;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Id.leftBar = global::XamDataGridSample.Droid.Resource.Id.leftBar;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Id.rightBar = global::XamDataGridSample.Droid.Resource.Id.rightBar;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Id.swipetorefreshbar = global::XamDataGridSample.Droid.Resource.Id.swipetorefreshbar;
			global::DevExpress.Mobile.DataGrid.Android.Resource.String.library_name = global::XamDataGridSample.Droid.Resource.String.library_name;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Style.DarkPopupMenu = global::XamDataGridSample.Droid.Resource.Style.DarkPopupMenu;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Style.DarkPopupMenuTextAppearanceLarge = global::XamDataGridSample.Droid.Resource.Style.DarkPopupMenuTextAppearanceLarge;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Style.DarkPopupMenuTextAppearanceSmall = global::XamDataGridSample.Droid.Resource.Style.DarkPopupMenuTextAppearanceSmall;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Style.GridThemeDark = global::XamDataGridSample.Droid.Resource.Style.GridThemeDark;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Style.GridThemeLight = global::XamDataGridSample.Droid.Resource.Style.GridThemeLight;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Style.LightPopupMenu = global::XamDataGridSample.Droid.Resource.Style.LightPopupMenu;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Style.LightPopupMenuTextAppearanceLarge = global::XamDataGridSample.Droid.Resource.Style.LightPopupMenuTextAppearanceLarge;
			global::DevExpress.Mobile.DataGrid.Android.Resource.Style.LightPopupMenuTextAppearanceSmall = global::XamDataGridSample.Droid.Resource.Style.LightPopupMenuTextAppearanceSmall;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::XamDataGridSample.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::XamDataGridSample.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int black = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int blue = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int gray = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int green = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int red = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int theme_dark_segmented_radio_button_text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int theme_default_segmented_radio_button_text = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int segment_grey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int segment_grey_focus = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int segment_grey_press = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int segment_left_off = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int segment_left_off_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int segment_left_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int segment_middle_off = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int segment_middle_off_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int segment_middle_on = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int segment_off = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int segment_off_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int segment_on = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int segment_radio_grey_left = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int segment_radio_grey_left_focus = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int segment_radio_grey_left_press = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int segment_radio_grey_middle = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int segment_radio_grey_middle_focus = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int segment_radio_grey_middle_press = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int segment_radio_grey_right = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int segment_radio_grey_right_focus = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int segment_radio_grey_right_press = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int segment_radio_white_left = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int segment_radio_white_left_focus = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int segment_radio_white_left_press = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int segment_radio_white_middle = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int segment_radio_white_middle_focus = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int segment_radio_white_middle_press = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int segment_radio_white_right = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int segment_radio_white_right_focus = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int segment_radio_white_right_press = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int segment_right_off = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int segment_right_off_pressed = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int segment_right_on = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int segment_white = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int segment_white_focus = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int segment_white_press = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int theme_dark_segment_button = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int theme_dark_segment_radio_left = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int theme_dark_segment_radio_middle = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int theme_dark_segment_radio_right = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int theme_default_segment_button = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int theme_default_segment_radio_left = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int theme_default_segment_radio_middle = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int theme_default_segment_radio_right = 2130837548;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int leftBar = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int rightBar = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int swipetorefreshbar = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int library_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060005
			public const int DarkPopupMenu = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int DarkPopupMenuTextAppearanceLarge = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int DarkPopupMenuTextAppearanceSmall = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int GridThemeDark = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int GridThemeLight = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int LightPopupMenu = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int LightPopupMenuTextAppearanceLarge = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int LightPopupMenuTextAppearanceSmall = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
